"""
Builds the R2Size brand mark ("Ticker field", chosen 2026-10-05) as plain SVG paths.

    ⌊R2⌋SIZE   R2 in Geist Mono 600 inside floor brackets; SIZE in Geist Mono 400, tracked.

The floor brackets are the sizing rule (quantities always round down). Everything is converted
to outlines, so no font is needed wherever the mark appears.

Run (needs Python with fontTools + brotli; not part of the app build):
    python scripts/brand/make_brand.py path/to/GeistMono-Variable.woff2
The font is Geist Mono (OFL) from https://github.com/vercel/geist-font (npm `geist`).

Writes:
    src/ui/app/brand-paths.ts          header wordmark + mark paths (currentColor)
    public/favicon.svg                 bold cut for 16-32 px
    scripts/brand/icon-*.svg           sources that scripts/make-icons.mjs renders to PNG
"""

import sys
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = Path(__file__).resolve().parents[2]
INK = '#111214'
PAPER = '#ecebe6'

# Geometry in font units (1000/em), y up from the baseline. Cap height is 710.
CAP = 710
OVER = 150  # brackets reach this far above the caps and below the baseline


def glyph_paths(font_path, weight, text, x0, tracking):
    """Outlines for `text` at `weight`, starting at x0, as SVG path data (y flipped later)."""
    font = instancer.instantiateVariableFont(TTFont(font_path), {'wght': weight})
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    parts = []
    x = x0
    for ch in text:
        g = glyphs[cmap[ord(ch)]]
        pen = SVGPathPen(glyphs, ntos=lambda v: f'{v:.0f}')
        # Flip y so the outline is in SVG space: y_svg = (CAP + OVER) - y.
        g.draw(TransformPen(pen, (1, 0, 0, -1, x, CAP + OVER)))
        parts.append(pen.getCommands())
        x += g.width + tracking
    return ' '.join(parts), x


def bracket(x_outer, stroke, foot, right=False):
    """A floor bracket: a vertical stroke plus a foot, as a filled path in SVG space."""
    top, bottom = 0, CAP + 2 * OVER
    if not right:
        return (
            f'M{x_outer} {top}H{x_outer + stroke}V{bottom - stroke}H{x_outer + foot}'
            f'V{bottom}H{x_outer}Z'
        )
    return (
        f'M{x_outer - stroke} {top}H{x_outer}V{bottom}H{x_outer - foot}'
        f'V{bottom - stroke}H{x_outer - stroke}Z'
    )


def mark(font_path, weight=600, stroke=110, foot=300, gap=175):
    """⌊R2⌋ only. Returns (path data, width, height)."""
    # R's left side bearing is ~64 and 2's right is ~46 at these weights.
    r2_x = stroke + gap - 64
    r2, r2_end = glyph_paths(font_path, weight, 'R2', r2_x, 0)
    ink_end = r2_end - 46
    right_outer = ink_end + gap + stroke
    d = ' '.join(
        [bracket(0, stroke, foot), r2, bracket(right_outer, stroke, foot, right=True)]
    )
    return d, right_outer, CAP + 2 * OVER


def wordmark(font_path):
    """⌊R2⌋SIZE. Returns (path data, width, height)."""
    d, mark_w, h = mark(font_path)
    size_x = mark_w + 210 - 44  # S has a ~44 left side bearing
    size, size_end = glyph_paths(font_path, 400, 'SIZE', size_x, 111)
    return f'{d} {size}', round(size_end - 111 - 70), h


def icon_svg(d, w, h, box, scale_to, ground, radius=0, ink=INK):
    """A square icon with the mark centred, `scale_to` of the box wide."""
    s = scale_to * box / w
    tx = (box - w * s) / 2
    ty = (box - h * s) / 2
    rect = f'<rect width="{box}" height="{box}" rx="{radius}" fill="{ground}"/>'
    path = f'<path transform="translate({tx:.2f} {ty:.2f}) scale({s:.5f})" fill="{ink}" d="{d}"/>'
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {box} {box}">'
        f'{rect}{path}</svg>\n'
    )


def main():
    font_path = sys.argv[1]
    word_d, word_w, word_h = wordmark(font_path)
    mark_d, mark_w, mark_h = mark(font_path)
    bold_d, bold_w, bold_h = mark(font_path, weight=800, stroke=150, foot=330, gap=140)

    (ROOT / 'src/ui/app/brand-paths.ts').write_text(
        '// Generated by scripts/brand/make_brand.py. Do not edit by hand.\n'
        '// The R2Size mark, "Ticker field": ⌊R2⌋SIZE in Geist Mono, as outlines.\n'
        f'export const WORDMARK = {{ width: {word_w}, height: {word_h}, d: {word_d!r} }} as const;\n'
        f'export const MARK = {{ width: {mark_w}, height: {mark_h}, d: {mark_d!r} }} as const;\n',
        encoding='utf-8',
    )

    public = ROOT / 'public'
    public.mkdir(exist_ok=True)
    (public / 'favicon.svg').write_text(
        icon_svg(bold_d, bold_w, bold_h, 100, 0.84, PAPER, radius=20), encoding='utf-8'
    )

    brand = ROOT / 'scripts/brand'
    # App icons: the mark at ~64% width; maskable keeps it inside the 80% safe circle.
    (brand / 'icon-any.svg').write_text(icon_svg(mark_d, mark_w, mark_h, 512, 0.64, PAPER), encoding='utf-8')
    (brand / 'icon-maskable.svg').write_text(icon_svg(mark_d, mark_w, mark_h, 512, 0.54, PAPER), encoding='utf-8')
    (brand / 'icon-small.svg').write_text(icon_svg(bold_d, bold_w, bold_h, 512, 0.74, PAPER), encoding='utf-8')
    # Social preview: the wordmark on the app background.
    s = 0.62 * 1200 / word_w
    (brand / 'og.svg').write_text(
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630">'
        '<rect width="1200" height="630" fill="#08090a"/>'
        f'<path transform="translate({(1200 - word_w * s) / 2:.2f} {(630 - word_h * s) / 2 - 40:.2f}) '
        f'scale({s:.5f})" fill="#f7f8f8" d="{word_d}"/>'
        '</svg>\n',
        encoding='utf-8',
    )
    print('wordmark', word_w, 'x', word_h, '| mark', mark_w, 'x', mark_h)


if __name__ == '__main__':
    main()
