/**
 * The one source of R2Size's security policy (architecture §7, ADR-006/009). The build writes it
 * twice: as a <meta> tag in index.html (defence in depth, production builds only) and as the
 * Cloudflare Pages `_headers` file. Tests check the two agree.
 */

/** The page policy. `connect-src 'none'` is what makes "nothing leaves your device" enforceable. */
const PAGE_DIRECTIVES = [
  ['default-src', "'none'"],
  ['script-src', "'self'"],
  ['style-src', "'self'"],
  ['img-src', "'self'"],
  ['font-src', "'self'"],
  ['manifest-src', "'self'"],
  ['worker-src', "'self'"],
  ['connect-src', "'none'"],
  ['form-action', "'none'"],
  ['base-uri', "'none'"],
  ['object-src', "'none'"],
  ['frame-ancestors', "'none'"],
  ['upgrade-insecure-requests', ''],
  ['require-trusted-types-for', "'script'"],
  // One policy, "default", which only lets the service worker's /sw.js through
  // (src/infra/trusted-types.ts). 'none' blocked registering the worker at all.
  ['trusted-types', 'default'],
] as const;

/** A <meta> policy cannot carry these; they only work as a response header. */
// upgrade-insecure-requests: production is HTTPS-only anyway, and in a meta tag WebKit also applies it
// to http://localhost, which breaks local previews and tests.
const HEADER_ONLY = new Set([
  'frame-ancestors',
  'report-uri',
  'report-to',
  'sandbox',
  'upgrade-insecure-requests',
]);

const join = (directives: readonly (readonly [string, string])[]) =>
  directives.map(([name, value]) => (value ? `${name} ${value}` : name)).join('; ');

export const PAGE_CSP_HEADER = join(PAGE_DIRECTIVES);
export const PAGE_CSP_META = join(PAGE_DIRECTIVES.filter(([name]) => !HEADER_ONLY.has(name)));

/**
 * The service worker fetches the app's own files to precache them, so it gets its own policy:
 * the page's `connect-src 'none'` would stop it caching anything.
 */
export const WORKER_CSP = "default-src 'none'; script-src 'self'; connect-src 'self'";

const SECURITY_HEADERS: readonly (readonly [string, string])[] = [
  ['Referrer-Policy', 'no-referrer'],
  ['X-Content-Type-Options', 'nosniff'],
  ['Permissions-Policy', 'camera=(), microphone=(), geolocation=(), payment=(), usb=()'],
  ['Cross-Origin-Opener-Policy', 'same-origin'],
  ['Cross-Origin-Resource-Policy', 'same-origin'],
  ['Strict-Transport-Security', 'max-age=31536000; includeSubDomains'],
];

const NO_CACHE = 'no-cache';
const IMMUTABLE = 'public, max-age=31536000, immutable';

/** Cloudflare Pages `_headers` (https://developers.cloudflare.com/pages/configuration/headers/). */
export const headersFile = (): string => {
  const block = (path: string, lines: readonly string[]) =>
    [path, ...lines.map((line) => `  ${line}`)].join('\n');
  return [
    '# Generated by vite.config.ts from config/security-policy.ts. Do not edit by hand.',
    block('/*', [
      `Content-Security-Policy: ${PAGE_CSP_HEADER}`,
      ...SECURITY_HEADERS.map(([name, value]) => `${name}: ${value}`),
    ]),
    // "!" removes the page policy that /* attached, before the worker's own policy is set.
    block('/sw.js', [
      '! Content-Security-Policy',
      `Content-Security-Policy: ${WORKER_CSP}`,
      `Cache-Control: ${NO_CACHE}`,
    ]),
    block('/assets/*', [`Cache-Control: ${IMMUTABLE}`]),
    block('/', [`Cache-Control: ${NO_CACHE}`]),
    block('/index.html', [`Cache-Control: ${NO_CACHE}`]),
    block('/manifest.webmanifest', [`Cache-Control: ${NO_CACHE}`]),
    '',
  ].join('\n\n');
};
